name: Android CI

on: [ push, pull_request ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spotless-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Android SDK License
        run: yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager --licenses

      - name: spotlessCheck with Gradle
        run: ./gradlew spotlessCheck

  connected-android-test:
    needs: build
    runs-on: macos-latest
    timeout-minutes: 60

    strategy:
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast: false
      matrix:
        include:
          - api-level: 30
            target: google_apis
          - api-level: 28
            target: default
          - api-level: 26
            target: default
          - api-level: 24
            target: default
          - api-level: 22
            target: default

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Android SDK License
        run: (while sleep 3; do echo "y"; done) | /Users/runner/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build tests
        run: ./gradlew assembleAndroidTest

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 40
        with:
          api-level: ${{ matrix.api-level }}
          profile: 4in WVGA (Nexus S)
          target: ${{ matrix.target }}
          ram-size: 2048M
          script: |
            adb logcat > logcat.txt &
            ./gradlew connectedCheck

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.api-level }}-${{ matrix.target }}
          path: logcat.txt

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ matrix.api-level }}-${{ matrix.target }}
          path: "**/build/outputs/**/connected/**/*.xml"

  build:
    needs: spotless-check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Apply Signing
        if: ${{ github.event_name != 'pull_request' }}
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: ./.github/apply_signing.sh

      - uses: pnpm/action-setup@v2
        with:
          version: '6.23.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Fetch maskbook
        run: ./.github/fetch_maskbook.sh
        
      - name: Build with Gradle
        run: ./gradlew assemble --no-daemon --stacktrace

      - name: Upload build outputs
        uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: ./app/build/outputs

      - name: Upload build reports
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: ./app/build/reports
