name: Android CI

on: [push, pull_request]

jobs:
  spotless-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Android SDK License
        run: yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager --licenses

      - name: spotlessCheck with Gradle
        run: ./gradlew spotlessCheck

  build:
    needs: spotless-check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Apply Signing
      if: ${{ github.event_name != 'pull_request' }}
      env:
        ALIAS: ${{ secrets.ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      run: ./.github/apply_signing.sh

    - uses: pnpm/action-setup@v2
      with:
        version: '6.23.1'
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Fetch maskbook
      run: ./.github/fetch_maskbook.sh

    - name: Build with Gradle
      run: ./gradlew assemble --stacktrace

    - name: Upload build outputs
      uses: actions/upload-artifact@v2
      with:
        name: build-outputs
        path: ./app/build/outputs
        
    - name: Upload build reports
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: ./app/build/reports
